apiVersion: v1
kind: Service
metadata:
  name: rentorbit-web
  namespace: ${KUBE_NAMESPACE}
  labels:
    app.kubernetes.io/name: rentorbit-web
    app.kubernetes.io/part-of: rentorbit
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rentorbit-web
  ports:
    - name: http
      port: 3000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: rentorbit-api
  namespace: ${KUBE_NAMESPACE}
  labels:
    app.kubernetes.io/name: rentorbit-api
    app.kubernetes.io/part-of: rentorbit
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rentorbit-api
  ports:
    - name: http
      port: 4000
      targetPort: http
