import { normalizeListingImageUrl } from "./listing-images.js";
import type { ResourceListing } from "./types.js";

type GeneratedListingSeed = {
  id: string;
  kind: ResourceListing["kind"];
  category: string;
  subCategory: string;
  title: string;
  description: string;
  image: string;
  alt: string;
  county: string;
  town: string;
  area: string;
  latitude: number;
  longitude: number;
  mode: ResourceListing["modeRules"][number]["mode"];
  billingMetric: ResourceListing["modeRules"][number]["pricing"]["billingMetric"];
  rate: number;
  minimumUnits: number;
  deposit?: number;
  countrywide?: boolean;
  deliveryModes: ResourceListing["logistics"]["deliveryModes"];
  setupTimeMinutes?: number;
  rating: number;
  reviewCount: number;
};

const seededAt = "2026-05-24T12:00:00+03:00";

const generatedListingSeeds: GeneratedListingSeed[] = [
  {
    id: "lst_events_tent_nairobi_005",
    kind: "good",
    category: "events",
    subCategory: "tents",
    title: "White Event Tent and Canopy Set",
    description: "Modular tent set for garden parties, church functions, launches, and county activations.",
    image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=900&q=80",
    alt: "Outdoor event tent with seating",
    county: "Nairobi",
    town: "Karen",
    area: "Karen and Langata",
    latitude: -1.3192,
    longitude: 36.7062,
    mode: "owner_operated",
    billingMetric: "daily",
    rate: 14000,
    minimumUnits: 1,
    deposit: 12000,
    deliveryModes: ["local_delivery"],
    setupTimeMinutes: 120,
    rating: 4.8,
    reviewCount: 33
  },
  {
    id: "lst_events_chairs_kiambu_006",
    kind: "good",
    category: "events",
    subCategory: "chairs",
    title: "Chiavari Chairs and Round Tables",
    description: "Clean event seating bundle with optional setup crew and linen coordination.",
    image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=900&q=80",
    alt: "Event chairs and tables in a decorated hall",
    county: "Kiambu",
    town: "Ruiru",
    area: "Ruiru, Juja, and Thika Road",
    latitude: -1.1451,
    longitude: 36.9662,
    mode: "owner_operated",
    billingMetric: "daily",
    rate: 9500,
    minimumUnits: 1,
    deposit: 8000,
    deliveryModes: ["local_delivery", "regional_delivery"],
    setupTimeMinutes: 90,
    rating: 4.7,
    reviewCount: 21
  },
  {
    id: "lst_electronics_camera_nairobi_007",
    kind: "good",
    category: "electronics",
    subCategory: "camera",
    title: "Canon R6 Camera and Lens Kit",
    description: "Mirrorless camera kit with 24-70mm lens, batteries, cards, and cage.",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80",
    alt: "Professional camera kit on a desk",
    county: "Nairobi",
    town: "Kilimani",
    area: "Kilimani and Hurlingham",
    latitude: -1.2921,
    longitude: 36.782,
    mode: "self_operated",
    billingMetric: "daily",
    rate: 7500,
    minimumUnits: 1,
    deposit: 25000,
    countrywide: true,
    deliveryModes: ["pickup", "local_delivery", "countrywide_delivery"],
    rating: 4.9,
    reviewCount: 44
  },
  {
    id: "lst_electronics_drone_nakuru_008",
    kind: "good",
    category: "electronics",
    subCategory: "drone",
    title: "DJI Drone with Licensed Pilot Option",
    description: "Aerial shoot drone for real estate, events, farms, and construction progress videos.",
    image: "https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=900&q=80",
    alt: "Drone flying above an outdoor landscape",
    county: "Nakuru",
    town: "Naivasha",
    area: "Naivasha and south Nakuru",
    latitude: -0.7172,
    longitude: 36.431,
    mode: "owner_operated",
    billingMetric: "daily",
    rate: 22000,
    minimumUnits: 1,
    deliveryModes: ["local_delivery", "regional_delivery"],
    setupTimeMinutes: 30,
    rating: 4.8,
    reviewCount: 19
  },
  {
    id: "lst_vehicle_moving_truck_mombasa_009",
    kind: "good",
    category: "vehicles",
    subCategory: "moving_truck",
    title: "Closed-Body Moving Truck",
    description: "Medium truck for house moves, stock transfers, and event logistics with driver option.",
    image: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=900&q=80",
    alt: "Moving truck parked near a loading area",
    county: "Mombasa",
    town: "Changamwe",
    area: "Changamwe and island access roads",
    latitude: -4.0333,
    longitude: 39.6278,
    mode: "owner_operated",
    billingMetric: "daily",
    rate: 12000,
    minimumUnits: 1,
    deposit: 10000,
    deliveryModes: ["local_delivery", "regional_delivery"],
    rating: 4.6,
    reviewCount: 24
  },
  {
    id: "lst_vehicle_delivery_bike_kisumu_010",
    kind: "service",
    category: "vehicles",
    subCategory: "courier",
    title: "Errand and Light Delivery Rider",
    description: "Motorbike courier for documents, parcels, small stock, and same-day pickups.",
    image: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=900&q=80",
    alt: "Motorbike rider on a city street",
    county: "Kisumu",
    town: "Kondele",
    area: "Kondele, CBD, and Milimani",
    latitude: -0.0818,
    longitude: 34.7677,
    mode: "operator_only",
    billingMetric: "hourly",
    rate: 850,
    minimumUnits: 2,
    deliveryModes: ["local_delivery"],
    rating: 4.7,
    reviewCount: 31
  },
  {
    id: "lst_fashion_gown_uasingishu_011",
    kind: "good",
    category: "fashion",
    subCategory: "wedding",
    title: "Designer Wedding Gown Rental",
    description: "Cleaned and fitted bridal gown with veil, garment bag, and pickup appointments.",
    image: "https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=900&q=80",
    alt: "White wedding gown hanging in a boutique",
    county: "Uasin Gishu",
    town: "Eldoret",
    area: "Eldoret CBD and Elgon View",
    latitude: 0.5143,
    longitude: 35.2698,
    mode: "self_operated",
    billingMetric: "daily",
    rate: 5500,
    minimumUnits: 1,
    deposit: 10000,
    countrywide: true,
    deliveryModes: ["pickup", "countrywide_delivery"],
    rating: 4.8,
    reviewCount: 16
  },
  {
    id: "lst_home_carpet_cleaner_kiambu_012",
    kind: "good",
    category: "home",
    subCategory: "cleaning_machine",
    title: "Carpet Cleaner and Wet Vacuum",
    description: "Deep-cleaning machine for carpets, sofas, mattresses, and car interiors.",
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80",
    alt: "Cleaning supplies and vacuum equipment",
    county: "Kiambu",
    town: "Kikuyu",
    area: "Kikuyu and Kabete",
    latitude: -1.2463,
    longitude: 36.6629,
    mode: "self_operated",
    billingMetric: "daily",
    rate: 2800,
    minimumUnits: 1,
    deposit: 6000,
    deliveryModes: ["pickup", "local_delivery"],
    rating: 4.5,
    reviewCount: 13
  },
  {
    id: "lst_tools_garden_meru_013",
    kind: "good",
    category: "tools",
    subCategory: "garden",
    title: "Garden Tools and Brush Cutter Kit",
    description: "Brush cutter, hedge trimmer, rake set, extension cable, and safety kit.",
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=900&q=80",
    alt: "Garden tools leaning against a wall",
    county: "Meru",
    town: "Makutano",
    area: "Makutano and central Meru",
    latitude: 0.047,
    longitude: 37.6496,
    mode: "self_operated",
    billingMetric: "daily",
    rate: 3200,
    minimumUnits: 1,
    deposit: 7000,
    deliveryModes: ["pickup", "local_delivery"],
    rating: 4.6,
    reviewCount: 17
  },
  {
    id: "lst_electronics_projector_kisii_014",
    kind: "good",
    category: "electronics",
    subCategory: "projector",
    title: "Projector, Screen, and Presenter Kit",
    description: "Bright projector bundle for training, worship, movie nights, and boardroom sessions.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80",
    alt: "Projection and presentation setup",
    county: "Kisii",
    town: "Kisii Town",
    area: "Kisii town center",
    latitude: -0.6773,
    longitude: 34.7796,
    mode: "self_operated",
    billingMetric: "daily",
    rate: 4200,
    minimumUnits: 1,
    deposit: 8000,
    countrywide: true,
    deliveryModes: ["pickup", "local_delivery", "countrywide_delivery"],
    rating: 4.4,
    reviewCount: 12
  },
  {
    id: "lst_spaces_meeting_room_nairobi_015",
    kind: "service",
    category: "spaces",
    subCategory: "meeting_room",
    title: "Quiet Meeting Room for Teams",
    description: "Private meeting room with screen, whiteboard, water, and reliable Wi-Fi.",
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80",
    alt: "Modern meeting room with table and chairs",
    county: "Nairobi",
    town: "Upper Hill",
    area: "Upper Hill business district",
    latitude: -1.3009,
    longitude: 36.8219,
    mode: "self_operated",
    billingMetric: "hourly",
    rate: 1800,
    minimumUnits: 2,
    deliveryModes: ["pickup"],
    rating: 4.7,
    reviewCount: 29
  },
  {
    id: "lst_spaces_storage_yard_machakos_016",
    kind: "service",
    category: "spaces",
    subCategory: "yard",
    title: "Secure Storage Yard and Loading Bay",
    description: "Short-term yard space for materials, vehicles, event stock, and contractor staging.",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=900&q=80",
    alt: "Warehouse loading yard with pallets",
    county: "Machakos",
    town: "Athi River",
    area: "Athi River industrial belt",
    latitude: -1.4547,
    longitude: 36.9784,
    mode: "self_operated",
    billingMetric: "daily",
    rate: 5000,
    minimumUnits: 1,
    deliveryModes: ["pickup"],
    rating: 4.5,
    reviewCount: 9
  },
  {
    id: "lst_sports_bikes_nyeri_017",
    kind: "good",
    category: "sports",
    subCategory: "bikes",
    title: "Mountain Bikes for Trail Rides",
    description: "Maintained hardtail bikes with helmets, pump, and route briefing.",
    image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=900&q=80",
    alt: "Mountain bikes lined up outdoors",
    county: "Nyeri",
    town: "Naro Moru",
    area: "Naro Moru and Mount Kenya routes",
    latitude: -0.1667,
    longitude: 37.0167,
    mode: "self_operated",
    billingMetric: "daily",
    rate: 2200,
    minimumUnits: 1,
    deposit: 5000,
    deliveryModes: ["pickup", "local_delivery"],
    rating: 4.9,
    reviewCount: 35
  },
  {
    id: "lst_sports_camping_nakuru_018",
    kind: "good",
    category: "sports",
    subCategory: "camping",
    title: "Camping Kit for Four People",
    description: "Tent, sleeping mats, lanterns, gas stove, cookware, and folding chairs.",
    image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=900&q=80",
    alt: "Camping tent in a forest campsite",
    county: "Nakuru",
    town: "Naivasha",
    area: "Naivasha lake corridor",
    latitude: -0.7172,
    longitude: 36.431,
    mode: "self_operated",
    billingMetric: "daily",
    rate: 3800,
    minimumUnits: 1,
    deposit: 6000,
    countrywide: true,
    deliveryModes: ["pickup", "regional_delivery", "countrywide_delivery"],
    rating: 4.6,
    reviewCount: 22
  },
  {
    id: "lst_services_photographer_mombasa_019",
    kind: "service",
    category: "professional_services",
    subCategory: "photography",
    title: "Event Photographer and Same-Day Preview",
    description: "Photographer for birthdays, graduations, corporate events, and beach ceremonies.",
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=900&q=80",
    alt: "Photographer capturing a wedding moment",
    county: "Mombasa",
    town: "Bamburi",
    area: "Bamburi and north coast venues",
    latitude: -3.9969,
    longitude: 39.715,
    mode: "operator_only",
    billingMetric: "hourly",
    rate: 3500,
    minimumUnits: 3,
    deliveryModes: ["local_delivery", "regional_delivery"],
    setupTimeMinutes: 20,
    rating: 4.8,
    reviewCount: 41
  },
  {
    id: "lst_services_electrician_kiambu_020",
    kind: "service",
    category: "professional_services",
    subCategory: "electrical",
    title: "Certified Event Power Technician",
    description: "Temporary wiring, generator changeover, lighting checks, and power safety supervision.",
    image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=900&q=80",
    alt: "Electrical technician working on wiring",
    county: "Kiambu",
    town: "Thika",
    area: "Thika and Kiambu industrial zones",
    latitude: -1.0332,
    longitude: 37.0693,
    mode: "operator_only",
    billingMetric: "hourly",
    rate: 2600,
    minimumUnits: 3,
    deliveryModes: ["local_delivery", "regional_delivery"],
    setupTimeMinutes: 30,
    rating: 4.7,
    reviewCount: 28
  },
  {
    id: "lst_domestic_cleaning_nairobi_021",
    kind: "service",
    category: "domestic_help",
    subCategory: "cleaning",
    title: "Deep Cleaning Team for Homes",
    description: "Two-person cleaning team for move-ins, post-event cleanup, kitchens, and bathrooms.",
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80",
    alt: "Home cleaning crew with supplies",
    county: "Nairobi",
    town: "South B",
    area: "South B, South C, and Industrial Area",
    latitude: -1.317,
    longitude: 36.842,
    mode: "operator_only",
    billingMetric: "hourly",
    rate: 1600,
    minimumUnits: 4,
    deliveryModes: ["local_delivery"],
    rating: 4.5,
    reviewCount: 36
  },
  {
    id: "lst_domestic_chef_mombasa_022",
    kind: "personnel",
    category: "domestic_help",
    subCategory: "cooking",
    title: "Private Chef for Home Events",
    description: "Chef for family dinners, small parties, meal prep, and coastal menus.",
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=900&q=80",
    alt: "Chef preparing food in a kitchen",
    county: "Mombasa",
    town: "Mtwapa",
    area: "Mtwapa and Nyali homes",
    latitude: -3.9475,
    longitude: 39.7444,
    mode: "operator_only",
    billingMetric: "daily",
    rate: 6500,
    minimumUnits: 1,
    deliveryModes: ["local_delivery"],
    setupTimeMinutes: 60,
    rating: 4.9,
    reviewCount: 20
  },
  {
    id: "lst_labor_loaders_nakuru_023",
    kind: "personnel",
    category: "casual_labor",
    subCategory: "loaders",
    title: "Verified Loaders for Moving Day",
    description: "Two to six loaders for house moves, stock loading, and event teardown.",
    image: "https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?auto=format&fit=crop&w=900&q=80",
    alt: "Workers carrying boxes at a site",
    county: "Nakuru",
    town: "Free Area",
    area: "Free Area, Shabab, and CBD",
    latitude: -0.3031,
    longitude: 36.08,
    mode: "operator_only",
    billingMetric: "hourly",
    rate: 1400,
    minimumUnits: 3,
    deliveryModes: ["local_delivery"],
    rating: 4.6,
    reviewCount: 25
  },
  {
    id: "lst_labor_farm_uasingishu_024",
    kind: "personnel",
    category: "casual_labor",
    subCategory: "farm_help",
    title: "Seasonal Farm Support Crew",
    description: "Casual farm hands for planting, harvesting, sorting, and packing days.",
    image: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=900&q=80",
    alt: "Farm workers in a field",
    county: "Uasin Gishu",
    town: "Turbo",
    area: "Turbo and nearby farms",
    latitude: 0.6368,
    longitude: 35.0474,
    mode: "operator_only",
    billingMetric: "daily",
    rate: 1800,
    minimumUnits: 1,
    deliveryModes: ["local_delivery"],
    rating: 4.4,
    reviewCount: 14
  },
  {
    id: "lst_operator_excavator_machakos_025",
    kind: "personnel",
    category: "operators",
    subCategory: "machine_operator",
    title: "Excavator Operator for Short Jobs",
    description: "Experienced operator for grading, trenching, site clearing, and small civil works.",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=900&q=80",
    alt: "Excavator at a construction site",
    county: "Machakos",
    town: "Mlolongo",
    area: "Mlolongo and Syokimau",
    latitude: -1.3783,
    longitude: 36.9465,
    mode: "operator_only",
    billingMetric: "daily",
    rate: 9000,
    minimumUnits: 1,
    deliveryModes: ["regional_delivery"],
    rating: 4.7,
    reviewCount: 18
  },
  {
    id: "lst_operator_camera_nairobi_026",
    kind: "personnel",
    category: "operators",
    subCategory: "camera_operator",
    title: "Camera Operator for Live Events",
    description: "Camera operator for conferences, livestreams, worship services, and brand shoots.",
    image: "https://images.unsplash.com/photo-1551818255-e6e10975bc17?auto=format&fit=crop&w=900&q=80",
    alt: "Camera operator filming a live event",
    county: "Nairobi",
    town: "Roysambu",
    area: "Roysambu and Thika Road",
    latitude: -1.2187,
    longitude: 36.886,
    mode: "operator_only",
    billingMetric: "daily",
    rate: 8000,
    minimumUnits: 1,
    deliveryModes: ["local_delivery", "regional_delivery"],
    rating: 4.8,
    reviewCount: 26
  },
  {
    id: "lst_service_ac_mombasa_027",
    kind: "service",
    category: "professional_services",
    subCategory: "hvac",
    title: "Portable AC Setup Technician",
    description: "Portable cooling setup and technician for tents, pop-ups, rooms, and small venues.",
    image: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=900&q=80",
    alt: "Technician servicing air conditioning unit",
    county: "Mombasa",
    town: "Likoni",
    area: "Likoni and south coast access",
    latitude: -4.0926,
    longitude: 39.6614,
    mode: "owner_operated",
    billingMetric: "daily",
    rate: 7000,
    minimumUnits: 1,
    deliveryModes: ["local_delivery"],
    setupTimeMinutes: 45,
    rating: 4.5,
    reviewCount: 10
  },
  {
    id: "lst_electronics_laptops_nairobi_028",
    kind: "good",
    category: "electronics",
    subCategory: "laptops",
    title: "Training Laptop Pack of Ten",
    description: "Ten laptops for workshops, bootcamps, hiring tests, and temporary offices.",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",
    alt: "Laptops arranged on a training table",
    county: "Nairobi",
    town: "Parklands",
    area: "Parklands and Westlands",
    latitude: -1.2578,
    longitude: 36.8197,
    mode: "self_operated",
    billingMetric: "daily",
    rate: 16000,
    minimumUnits: 1,
    deposit: 40000,
    countrywide: true,
    deliveryModes: ["local_delivery", "regional_delivery", "countrywide_delivery"],
    rating: 4.6,
    reviewCount: 15
  },
  {
    id: "lst_events_lighting_kisumu_029",
    kind: "good",
    category: "events",
    subCategory: "lighting",
    title: "Stage Lighting and Truss Kit",
    description: "LED pars, moving heads, controller, compact truss, and technician option.",
    image: "https://images.unsplash.com/photo-1509824227185-9c5a01ceba0d?auto=format&fit=crop&w=900&q=80",
    alt: "Stage lighting in a concert venue",
    county: "Kisumu",
    town: "Dunga",
    area: "Dunga, Milimani, and CBD",
    latitude: -0.1133,
    longitude: 34.7519,
    mode: "owner_operated",
    billingMetric: "daily",
    rate: 18500,
    minimumUnits: 1,
    deposit: 20000,
    deliveryModes: ["local_delivery", "regional_delivery"],
    setupTimeMinutes: 100,
    rating: 4.7,
    reviewCount: 23
  },
  {
    id: "lst_vehicle_water_bowser_kajiado_030",
    kind: "good",
    category: "vehicles",
    subCategory: "water_bowser",
    title: "Water Bowser for Sites and Events",
    description: "Clean water delivery for construction sites, outdoor events, farms, and camps.",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
    alt: "Water delivery truck near an outdoor landscape",
    county: "Kajiado",
    town: "Kitengela",
    area: "Kitengela and Athi River corridor",
    latitude: -1.4793,
    longitude: 36.958,
    mode: "owner_operated",
    billingMetric: "daily",
    rate: 11000,
    minimumUnits: 1,
    deliveryModes: ["local_delivery", "regional_delivery"],
    rating: 4.4,
    reviewCount: 11
  },
  {
    id: "lst_service_barber_nairobi_031",
    kind: "service",
    category: "professional_services",
    subCategory: "grooming",
    title: "Mobile Barber for Shoots and Events",
    description: "On-location grooming for bridal parties, photoshoots, teams, and brand activations.",
    image: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=900&q=80",
    alt: "Barber tools and chair in a shop",
    county: "Nairobi",
    town: "Eastleigh",
    area: "Eastleigh, Pangani, and CBD",
    latitude: -1.2733,
    longitude: 36.8492,
    mode: "operator_only",
    billingMetric: "hourly",
    rate: 2200,
    minimumUnits: 2,
    deliveryModes: ["local_delivery"],
    setupTimeMinutes: 20,
    rating: 4.8,
    reviewCount: 30
  },
  {
    id: "lst_home_baby_seats_kiambu_032",
    kind: "good",
    category: "home",
    subCategory: "baby_gear",
    title: "Baby Car Seats and Travel Cot",
    description: "Clean travel bundle for visiting families, weekend trips, and temporary childcare needs.",
    image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=900&q=80",
    alt: "Baby gear and nursery setup",
    county: "Kiambu",
    town: "Limuru",
    area: "Limuru and Tigoni",
    latitude: -1.1076,
    longitude: 36.642,
    mode: "self_operated",
    billingMetric: "daily",
    rate: 1800,
    minimumUnits: 1,
    deposit: 3500,
    countrywide: true,
    deliveryModes: ["pickup", "local_delivery", "countrywide_delivery"],
    rating: 4.9,
    reviewCount: 17
  },
  {
    id: "lst_spaces_kiosk_mombasa_033",
    kind: "good",
    category: "spaces",
    subCategory: "pop_up",
    title: "Pop-Up Kiosk and Display Counter",
    description: "Portable kiosk for sampling, mall activations, market stalls, and beach promos.",
    image: "https://images.unsplash.com/photo-1556745757-8d76bdb6984b?auto=format&fit=crop&w=900&q=80",
    alt: "Retail display counter at a small business",
    county: "Mombasa",
    town: "Old Town",
    area: "Old Town and CBD",
    latitude: -4.0627,
    longitude: 39.6776,
    mode: "self_operated",
    billingMetric: "daily",
    rate: 4500,
    minimumUnits: 1,
    deposit: 5000,
    deliveryModes: ["pickup", "local_delivery"],
    rating: 4.3,
    reviewCount: 8
  },
  {
    id: "lst_operator_forklift_nairobi_034",
    kind: "personnel",
    category: "operators",
    subCategory: "forklift_operator",
    title: "Forklift Operator for Warehouse Shifts",
    description: "Certified forklift operator for stock counts, loading days, and short warehouse shifts.",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=900&q=80",
    alt: "Warehouse operator near pallets",
    county: "Nairobi",
    town: "Industrial Area",
    area: "Industrial Area and Mombasa Road",
    latitude: -1.3147,
    longitude: 36.852,
    mode: "operator_only",
    billingMetric: "daily",
    rate: 7500,
    minimumUnits: 1,
    deliveryModes: ["local_delivery"],
    rating: 4.6,
    reviewCount: 12
  }
];

function toGeneratedListing(seed: GeneratedListingSeed, index: number): ResourceListing {
  return {
    id: seed.id,
    ownerId: `usr_owner_seed_${(index % 8) + 1}`,
    kind: seed.kind,
    category: seed.category,
    subCategory: seed.subCategory,
    title: seed.title,
    description: seed.description,
    status: "active",
    media: [
      {
        id: `media_${seed.id.replace("lst_", "")}`,
        url: seed.image,
        alt: seed.alt,
        isPrimary: true
      }
    ],
    location: {
      country: "Kenya",
      county: seed.county,
      town: seed.town,
      generalArea: seed.area,
      exactCoordinates: { latitude: seed.latitude, longitude: seed.longitude },
      maxTravelRadiusKm: seed.kind === "good" ? 45 : 80,
      countrywideAvailable: seed.countrywide ?? false
    },
    modeRules: [
      {
        mode: seed.mode,
        label: seed.mode === "self_operated" ? "Self-operated rental" : seed.mode === "owner_operated" ? "Owner-operated booking" : "Operator booking",
        pricing: {
          billingMetric: seed.billingMetric,
          rate: { amount: seed.rate, currency: "KES" },
          minimumUnits: seed.minimumUnits,
          deposit: seed.deposit ? { amount: seed.deposit, currency: "KES" } : undefined,
          replacementValue: seed.deposit ? { amount: seed.deposit * 5, currency: "KES" } : undefined,
          platformFeeRate: seed.kind === "service" || seed.kind === "personnel" ? 0.1 : 0.08
        },
        requiresKyc: true,
        requiresDeposit: Boolean(seed.deposit)
      }
    ],
    logistics: {
      deliveryModes: seed.deliveryModes,
      returnRequirements: seed.kind === "good" ? "Owner records condition photos at handoff and return." : undefined,
      setupTimeMinutes: seed.setupTimeMinutes,
      overtimeRate:
        seed.billingMetric === "hourly"
          ? { amount: Math.round(seed.rate * 1.35), currency: "KES" }
          : undefined,
      providesOwnTransport: seed.kind !== "good"
    },
    unavailableWindows: index % 7 === 0 ? [{ start: "2026-06-16T08:00:00+03:00", end: "2026-06-16T18:00:00+03:00" }] : [],
    rating: seed.rating,
    reviewCount: seed.reviewCount,
    metadata: { seedCountyPriority: (index % 5) + 1 },
    createdAt: seededAt,
    updatedAt: seededAt
  };
}

function withPreparedListingMedia(listing: ResourceListing): ResourceListing {
  return {
    ...listing,
    media: listing.media.map((media) => ({
      ...media,
      url: normalizeListingImageUrl(media.url)
    })),
    metadata: {
      ...listing.metadata,
      imageAspectRatio: "5:7",
      imageCompressionQuality: 72
    }
  };
}

const baseSeededListings: ResourceListing[] = [
  {
    id: "lst_events_sound_nairobi_001",
    ownerId: "usr_owner_asha",
    kind: "good",
    category: "events",
    subCategory: "sound",
    title: "JBL PA Sound System with Optional Engineer",
    description: "Two powered tops, subwoofer, mixer, microphones, stands, and an owner-operated sound engineer option.",
    status: "active",
    media: [
      {
        id: "media_001",
        url: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=900&q=80",
        alt: "Live event sound mixer and stage equipment",
        isPrimary: true
      }
    ],
    location: {
      country: "Kenya",
      county: "Nairobi",
      town: "Westlands",
      generalArea: "Westlands and nearby estates",
      exactCoordinates: { latitude: -1.2641, longitude: 36.8028 },
      maxTravelRadiusKm: 40,
      countrywideAvailable: false
    },
    modeRules: [
      {
        mode: "self_operated",
        label: "Self-operated package",
        pricing: {
          billingMetric: "daily",
          rate: { amount: 8500, currency: "KES" },
          minimumUnits: 1,
          deposit: { amount: 25000, currency: "KES" },
          replacementValue: { amount: 180000, currency: "KES" },
          platformFeeRate: 0.08
        },
        requiresKyc: true,
        requiresDeposit: true
      },
      {
        mode: "owner_operated",
        label: "Engineer included",
        pricing: {
          billingMetric: "daily",
          rate: { amount: 18000, currency: "KES" },
          minimumUnits: 1,
          platformFeeRate: 0.08
        },
        requiresKyc: true,
        requiresDeposit: false
      }
    ],
    logistics: {
      deliveryModes: ["pickup", "local_delivery"],
      returnRequirements: "Return by 10:00 the next day unless amended in chat.",
      setupTimeMinutes: 90,
      overtimeRate: { amount: 2500, currency: "KES" },
      providesOwnTransport: true
    },
    unavailableWindows: [{ start: "2026-06-14T08:00:00+03:00", end: "2026-06-15T10:00:00+03:00" }],
    rating: 4.9,
    reviewCount: 42,
    metadata: { seedCountyPriority: 1, insuredByOwner: false },
    createdAt: "2026-05-24T12:00:00+03:00",
    updatedAt: "2026-05-24T12:00:00+03:00"
  },
  {
    id: "lst_tools_generator_kisumu_002",
    ownerId: "usr_owner_otieno",
    kind: "good",
    category: "tools",
    subCategory: "power",
    title: "7.5kVA Silent Generator",
    description: "Event and site generator with delivery available around Kisumu and regional dispatch on request.",
    status: "active",
    media: [
      {
        id: "media_002",
        url: "https://images.unsplash.com/photo-1509395176047-4a66953fd231?auto=format&fit=crop&w=900&q=80",
        alt: "Portable power generator and cables",
        isPrimary: true
      }
    ],
    location: {
      country: "Kenya",
      county: "Kisumu",
      town: "Milimani",
      generalArea: "Milimani, Kisumu",
      exactCoordinates: { latitude: -0.1022, longitude: 34.7617 },
      maxTravelRadiusKm: 80,
      countrywideAvailable: true
    },
    modeRules: [
      {
        mode: "self_operated",
        label: "Pickup or delivered generator",
        pricing: {
          billingMetric: "daily",
          rate: { amount: 6000, currency: "KES" },
          minimumUnits: 1,
          deposit: { amount: 15000, currency: "KES" },
          replacementValue: { amount: 125000, currency: "KES" },
          platformFeeRate: 0.08
        },
        requiresKyc: true,
        requiresDeposit: true
      }
    ],
    logistics: {
      deliveryModes: ["pickup", "local_delivery", "regional_delivery", "countrywide_delivery"],
      returnRequirements: "Fuel level and hour meter are photographed at pickup and return."
    },
    unavailableWindows: [],
    rating: 4.7,
    reviewCount: 18,
    metadata: { seedCountyPriority: 1, fuelPolicy: "return_same_level" },
    createdAt: "2026-05-24T12:00:00+03:00",
    updatedAt: "2026-05-24T12:00:00+03:00"
  },
  {
    id: "lst_personnel_loader_mombasa_003",
    ownerId: "usr_owner_mwikali",
    kind: "personnel",
    category: "casual_labor",
    subCategory: "event_crew",
    title: "Verified Event Setup Crew",
    description: "Three-person crew for tent setup, chairs, staging, loading, and teardown around the coast.",
    status: "active",
    media: [
      {
        id: "media_003",
        url: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=900&q=80",
        alt: "Outdoor event crew setting up a venue",
        isPrimary: true
      }
    ],
    location: {
      country: "Kenya",
      county: "Mombasa",
      town: "Nyali",
      generalArea: "Nyali and greater Mombasa",
      exactCoordinates: { latitude: -4.0435, longitude: 39.6682 },
      maxTravelRadiusKm: 65,
      countrywideAvailable: false
    },
    modeRules: [
      {
        mode: "operator_only",
        label: "Crew booking",
        pricing: {
          billingMetric: "hourly",
          rate: { amount: 1800, currency: "KES" },
          minimumUnits: 4,
          platformFeeRate: 0.1
        },
        requiresKyc: true,
        requiresDeposit: false
      }
    ],
    logistics: {
      deliveryModes: ["local_delivery"],
      setupTimeMinutes: 30,
      overtimeRate: { amount: 2400, currency: "KES" },
      providesOwnTransport: true
    },
    unavailableWindows: [],
    rating: 4.8,
    reviewCount: 27,
    metadata: { maxCrewSize: 6 },
    createdAt: "2026-05-24T12:00:00+03:00",
    updatedAt: "2026-05-24T12:00:00+03:00"
  },
  {
    id: "lst_space_studio_nakuru_004",
    ownerId: "usr_owner_wanjiku",
    kind: "service",
    category: "spaces",
    subCategory: "studio",
    title: "Podcast and Product Shoot Studio",
    description: "Small studio with lights, backdrops, table setup, and optional camera operator.",
    status: "active",
    media: [
      {
        id: "media_004",
        url: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=900&q=80",
        alt: "Recording studio with microphones and monitors",
        isPrimary: true
      }
    ],
    location: {
      country: "Kenya",
      county: "Nakuru",
      town: "Section 58",
      generalArea: "Section 58, Nakuru",
      exactCoordinates: { latitude: -0.3031, longitude: 36.0800 },
      maxTravelRadiusKm: 0,
      countrywideAvailable: false
    },
    modeRules: [
      {
        mode: "self_operated",
        label: "Studio only",
        pricing: {
          billingMetric: "hourly",
          rate: { amount: 2500, currency: "KES" },
          minimumUnits: 2,
          deposit: { amount: 5000, currency: "KES" },
          replacementValue: { amount: 80000, currency: "KES" },
          platformFeeRate: 0.08
        },
        requiresKyc: true,
        requiresDeposit: true
      },
      {
        mode: "owner_operated",
        label: "Operator included",
        pricing: {
          billingMetric: "hourly",
          rate: { amount: 4200, currency: "KES" },
          minimumUnits: 2,
          platformFeeRate: 0.08
        },
        requiresKyc: true,
        requiresDeposit: false
      }
    ],
    logistics: {
      deliveryModes: ["pickup"],
      setupTimeMinutes: 20,
      overtimeRate: { amount: 4500, currency: "KES" }
    },
    unavailableWindows: [],
    rating: 4.6,
    reviewCount: 11,
    metadata: { rooms: 2 },
    createdAt: "2026-05-24T12:00:00+03:00",
    updatedAt: "2026-05-24T12:00:00+03:00"
  },
  ...generatedListingSeeds.map(toGeneratedListing)
];

export const seededListings: ResourceListing[] = baseSeededListings.map(withPreparedListingMedia);
